[package]
name = "ntwscan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.1"
shared = { path = "../shared" }
tokio = "1.36.0"
