[package]
name = "hack_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
tokio = {version = "1.34.0", features = ["full"] }
termion = "2.0.3"
clap = "4.4.11"